spring:
  application:
    name: OdbItAppsRabbitmq
  rabbitmq:
    host: localhost # RabbitMQ host.
    port: 5672
odbitappsrabbitmq:
  queueName: dnp3/control
  topicExchangeName: odbitappsrabbitmq-dnp3-exchange
  payload: '{"DCTE.WinTms.AI55": 15}'
