spring:
  application:
    name: OdbItAppsRabbitmq
  rabbitmq:
    host: localhost # RabbitMQ host.
odbitappsrabbitmq:
  publish:
    queueName: itapps/point
    payload: '{"DCTE.WinTms.AI55": 15}'
    path: 'campus/building/dnps'
    routingKey: dnp3.point
    topicExchangeName: itapps-dnp3-pub-exchange
  subscribe:
    queueName: itapps/control
    topicExchangeName: itapps-dnp3-sub-exchange
    routingKey: dnp3.#
---
spring:
  config:
    activate:
      on-profile: LOCAL
odbitappsrabbitmq:
  subscribe:
    queueName: itapps/point
    topicExchangeName: itapps-dnp3-pub-exchange
---
spring:
  config:
    activate:
      on-profile: LOOP
odbitappsrabbitmq:
  subscribe:
    queueName: itapps/point
    topicExchangeName: itapps-dnp3-pub-exchange
---
spring:
  config:
    activate:
      on-profile: LOOP2
odbitappsrabbitmq:
  publish:
    queueName: itapps/control
    routingKey: dnp3.control
    topicExchangeName: itapps-dnp3-sub-exchange
  subscribe:
    queueName: itapps/control
    topicExchangeName: itapps-dnp3-sub-exchange
    routingKey: dnp3.#
---
spring:
  config:
    activate:
      on-profile: VOLTTRON
  rabbitmq:
    host: AZUSE-ARIPP02
    ssl:
      enabled: true
      trust-store: file:/opt/poc/keys/client_truststore.jks
      trust-store-password: test1234!
      verify-hostname: false
      key-store: file:/opt/poc/keys/client_keystore.p12
      key-store-password: client1234!
#    username: client1
#    password: client1234!
    virtual-host: volttron
---
spring:
  config:
    activate:
      on-profile: DEBUG
logging:
  level:
    org.springframework: trace
    com.rabbitmq: trace
