spring:
  application:
    name: OdbItAppsRabbitmq
  rabbitmq:
    host: localhost # RabbitMQ host.
odbitappsrabbitmq:
  publish:
    queueName: itapps/point
    payload: '{"DCTE.WinTms.AI55": 15}'
    routingKey: dnp3.point
    topicExchangeName: itapps-dnp3-pub-exchange
  subscribe:
    queueName: itapps/control
    topicExchangeName: itapps-dnp3-sub-exchange
    routingKey: dnp3.#
---
spring:
  config:
    activate:
      on-profile: LOCAL
odbitappsrabbitmq:
  subscribe:
    queueName: itapps/point
    topicExchangeName: itapps-dnp3-pub-exchange
---
spring:
  config:
    activate:
      on-profile: VOLTTRON
  rabbitmq:
    host: AZUSE-ARIPP02
    ssl:
      enabled: true
      trust-store: file:/home/t1adm-y.qu@preprod.nationalgrid.com/dev/keys/client_truststore.jks
      trust-store-password: test1234!
      verify-hostname: false
      key-store: file:/home/t1adm-y.qu@preprod.nationalgrid.com/dev/keys/client_keystore.p12
      key-store-password: client1234!
    username: client1
    password: client1234!
    virtual-host: volttron
odbitappsrabbitmq:
  subscribe:
    queueName: itapps/point
    topicExchangeName: itapps-dnp3-pub-exchange
logging:
  level:
    org.springframework: trace
    com.rabbitmq: trace
