spring:
  application:
    name: OdbItAppsRabbitmq
  rabbitmq:
    host: localhost # RabbitMQ host.
    port: 5672
odbitappsrabbitmq:
  publish:
    queueName: itapps/point
    payload: '{"DCTE.WinTms.AI55": 15}'
    routingKey: dnp3.point
    topicExchangeName: itapps-dnp3-pub-exchange
  subscribe:
    queueName: itapps/control
    topicExchangeName: itapps-dnp3-sub-exchange
    routingKey: dnp3.#
---
spring:
  config:
    activate:
      on-profile: LOCAL
odbitappsrabbitmq:
  subscribe:
    queueName: itapps/point
    topicExchangeName: itapps-dnp3-pub-exchange
---
spring:
  config:
    activate:
      on-profile: VOLTTRON
  rabbitmq:
    ssl:
      enabled: true
    port: 5671
odbitappsrabbitmq:
  subscribe:
    queueName: itapps/point
    topicExchangeName: itapps-dnp3-pub-exchange

